# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.5.1
_src_path: git+https://github.com/oca/oca-addons-repo-template
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: Define shift planning and organise the work of your organization's
  members.
repo_name: Shift Planning
repo_slug: shift-planning
travis_apt_packages: []
travis_apt_sources: []
